kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    app: fluentd
    version: v2
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: fluentd
    spec:
      volumes:
        - name: pos-files
          emptyDir: {}
        - name: host-logs
          hostPath:
            path: /var/log/
        - name: docker-logs
          hostPath:
            path: /var/lib/docker
      containers:
        - name: fluentd
          image: 'localhost:30001/fluentd-kubernetes-sumologic:0.9'
          env:
            - name: COLLECTOR_URL
              valueFrom:
                secretKeyRef:
                  name: sumologic
                  key: collector-url
          resources: {}
          volumeMounts:
            - name: host-logs
              readOnly: true
              mountPath: /var/log/
            - name: docker-logs
              readOnly: true
              mountPath: /var/lib/docker/
            - name: pos-files
              mountPath: /mnt/pos/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  updateStrategy:
    type: OnDelete
  templateGeneration: 3
status:
  currentNumberScheduled: 4
  numberMisscheduled: 0
  desiredNumberScheduled: 4
  numberReady: 4
  observedGeneration: 1
  updatedNumberScheduled: 4
  numberAvailable: 4
